services:
  postgres:
    image: postgres:latest
    container_name: explosive-pig-postgres-local # I had to name this because I have existing containers with the same name
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: