// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/classes": {
    params: {};
  };
  "/classes/add": {
    params: {};
  };
  "/teachers": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/classes" | "/classes/add" | "/teachers";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/classes/classes.tsx": {
    id: "routes/classes/classes";
    page: "/classes";
  };
  "routes/classes/add.tsx": {
    id: "routes/classes/add";
    page: "/classes/add";
  };
  "routes/teachers/teachers.tsx": {
    id: "routes/teachers/teachers";
    page: "/teachers";
  };
};